"""Blocklist of company names that have shown up as scam/phishing signups.

Hand-maintained reference (originally curated in inflow-ats). Every name here
was used in a real scam attempt. When a new one appears, just add a line to
RAW_NAMES in any casing/punctuation — it's normalized on load. Matched in
scripts.qualify against the normalized signup company name (exact match, so a
generic word like "saltwater" only blocks a company literally named that).
"""
from __future__ import annotations

import re

RAW_NAMES = [
    "a 2 zen clutter coaching",
    "adventures taken, llc",
    "agência alpha one",
    "alberta health services",
    "alphastone career",
    "amazon",
    "apple",
    "aramcon",
    "aspire lending",
    "audacy inc",
    "autohaven enthusiasts at unc charlotte",
    "b - rail consulting sarl",
    "bank of america",
    "bastet conseils",
    "bernecker's nursery",
    "berneckers nursery",
    "big mama's & papa's pizzeria",
    "big mamas & papas pizzeria",
    "bmo financial group",
    "briazzai",
    "canada's wonderland",
    "canadas wonderland",
    "chase",
    "coinlist",
    "colégio dom aguirre",
    "comconeo",
    "consciously aware coaching",
    "cosmetiklab",
    "cowan brown",
    "crescentsight media",
    "dadeland animal hospital",
    "daghe monte carlo",
    "dakota aviation",
    "david malin financial advice ltd",
    "denzler family dentistry",
    "dhl",
    "digital essentials",
    "ecosure insurance",
    "ekoda solutions ltd",
    "elevating work platforms",
    "fedex",
    "four seasons",
    "foundever",
    "gemini direct marketing solutions gmbh",
    "global policy ltd",
    "google",
    "groupe iprocia",
    "guggenheim partners llc",
    "hireup works",
    "ho' brah a tacos joint",
    "ho brah a tacos joint",
    "home craft construction company",
    "horizontal talent",
    "hp",
    "indeed",
    "intel",
    "intercontinental",
    "iron city premier realty",
    "iurapp",
    "jobsai",
    "jobs from worldwide",
    "jobsolutionsai",
    "john-deere",
    "justinus@buybm.one",
    "kandoul international transport",
    "keeptie",
    "kitagroup",
    "kroll restructuring",
    "lazard",
    "learnify research lab",
    "liberty roofing professionals",
    "lucky egg gameplay uk",
    "lululemon",
    "luz soluções ambientais",
    "lyria",
    "macstone solutions",
    "marriott",
    "mbt motors",
    "mcdonald's",
    "mcdonalds",
    "michael kors",
    "microsoft",
    "moneris",
    "mrkit",
    "nbconseil et recrutement",
    "neighbors emergency center",
    "netflix",
    "nextgen real estate",
    "palermo inmobiliaria",
    "paypal",
    "phoenix house",
    "physicsx",
    "plumber brother",
    "quizitive",
    "r r campus",
    "redes terapia sistemica",
    "re-value investments",
    "revalue investments",
    "river city science academy",
    "robert half",
    "robin knows",
    "royal bank",
    "rumi bose ltd.",
    "s&f advisory",
    "saisethsons hospitality group inc.",
    "sait",
    "saltwater",
    "save on foods",
    "self-made speaker",
    "sendero punto sano",
    "shewmaker & corman at law, pllc",
    "shoppers drug mart",
    "shower fusion",
    "staples",
    "starter staffing",
    "stitchy fish llc",
    "stocklock co.",
    "supernoya llc",
    "synct fl",
    "systemeu valley",
    "t-mobile",
    "tmobile",
    "tech hartford",
    "thar renewables",
    "the housing company",
    "the marketing circle uk",
    "the shop experts",
    "the ward team",
    "the zanzibar collection",
    "titan bird",
    "truesight dme billing software",
    "united nation",
    "united spine & joint center",
    "ups",
    "vanderlee transportbanden",
    "victor pumpen gmbh",
    "viix digita",
    "virtual business summit - mena",
    "virginia tech",
    "volf communications llc",
    "w advisory france",
    "walgreens",
    "walmart",
    "watkins talent solutions",
    "wellpowerment",
    "wells fargo",
    "windsor college",
    "wv ventures",
    "yukey",
    "zeta resolution",
    "zusamen",
]


def normalize_company(name: str) -> str:
    """Lowercase, drop punctuation, collapse whitespace — for blocklist match.

    So "McDonald's" and "mcdonalds" both land on the same key.
    """
    cleaned = re.sub(r"[^\w\s]", "", (name or "").lower())
    return " ".join(cleaned.split())


# Normalized set — de-dupes the punctuation variants kept in RAW_NAMES.
BLOCKED_COMPANY_NAMES = frozenset(
    key for key in (normalize_company(n) for n in RAW_NAMES) if key
)
